[package]
name = "diesel1739"
version = "0.1.0"
authors = ["Philip Jenvey <pjenvey@underboss.org>"]

[dependencies]
diesel = { version = "1.3", features = ["mysql", "r2d2"] }
diesel_migrations = { version = "1.3", features = ["mysql"] }
